[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
solc = "0.8.24"
fs_permissions = [{ access = "read", path = "./broadcast" }]
gas_reports = ["Foo"]

[rpc_endpoints]
world = "${WORLD_RPC_URL}"
worldSepolia = "${WORLD_SEPOLIA_RPC_URL}"

[etherscan]
world = { key = "${WORLD_ETHERSCAN_API_KEY}", url = "https://api.worldscan.org/api", chain = 480 }

[fuzz]
runs = 10
max_test_rejects = 10000

[invariant]
runs = 10
max_test_rejects = 1000